### ISSUE TITLE
Die Validierungsseite gibt mir immer einen Fehler zurück

### ISSUE THREAD

**Issue by UweGi** [swico/www.swiss-qr-invoice.org#36]
Ich erhalte seit heute folgende Fehlermeldung, wenn ich einen QR-Code prüfen möchte:
Die Anfrage ist fehlgeschlagen (siehe js logs für mehr Details)
Das Log gibt folgendes aus:
Access to XMLHttpRequest at 'https://partout.cresus.ch/swiss-qr-invoice/v2/decode' from origin 'https://www.swiss-qr-invoice.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
partout.cresus.ch/swiss-qr-invoice/v2/decode:1          Failed to load resource: net::ERR_FAILED
main-0bc60c0a4cd1cf3585b2.js:7 Network Error: ({ webService = { error = Just { errorCode = NetworkError, additionalInformation = "", message = "", stackTrace = "" }, decoding = { error = Nothing, raw = Nothing }, validation = { error = Nothing, validations = Nothing }, swicoLine = { error = Nothing, payload = Nothing }, alternativeProcedure1 = { error = Nothing, payload = Nothing }, alternativeProcedure2 = { error = Nothing, payload = Nothing }, generation = { error = Nothing, image = Nothing } }, language = SwissGerman, qrValidation = { hoveredValidations = [] }, dropZone = { hoverState = Normal }, tabs = Validation, files = [{ name = "swissqrbill.png", size = 7294, mimeType = Just (Image Png), blob = { name = "swissqrbill.png", lastModified = 1654668659439, lastModifiedDate = <Wed Jun 08 2022 08:10:59 GMT+0200 (Mitteleuropäische Sommerzeit)>, webkitRelativePath = "", size = 7294, type = "image/png", arrayBuffer = <function>, slice = <function>, stream = <function>, text = <function> } }] },{ type = "node", branches = [] })
3content.js:1 Uncaught Error: Extension context invalidated.
    at u.request (content.js:1:2322)
    at Object.notifyIframes (content.js:1:4808)
    at Ea.onMouseDown (content.js:1:132676)

Gestern hat es mit der hochgeladenen Datei noch funktioniert.

**Comment by bruno1305** [comment]
Am 19.08.22 wohl immer noch defekt.  Anscheinend spielt hier https://cresus.ch/ nicht mehr mit?

Access to XMLHttpRequest at 'https://partout.cresus.ch/swiss-qr-invoice/v2/decode' from origin 'https://www.swiss-qr-invoice.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
partout.cresus.ch/swiss-qr-invoice/v2/decode:1

Diese Alternative scheint zu gehen:  https://rest.qr-invoice.cloud/app/index.html#/
